name: todoapp_classic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: 
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: 
  build_runner: 

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-VariableFont_wght.ttf
    - family: TiltNeon
      fonts:
        - asset: fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf
    - family: YanoneKaffeesatz
      fonts:
        - asset: fonts/YanoneKaffeesatz-VariableFont_wght.ttf